import type { AdminRole, AppPermission } from '@/utils/permissions/roles';

export const permissionMatrix: Record<AdminRole, AppPermission[]> = {
  broker: [
    'dashboard.view',
    'users.view',
    'users.create',
    'users.verify',
    'users.suspend',
    'buyers.view',
    'sellers.view',
    'marketplace.view',
    'marketplace.review',
    'requests.view',
    'requests.assign',
    'deals.view',
    'deals.manage',
    'documents.view',
    'documents.verify',
    'analytics.view',
  ],
  agent: [
    'dashboard.view',
    'users.view',
    'users.create',
    'users.verify',
    'buyers.view',
    'sellers.view',
    'marketplace.view',
    'marketplace.review',
    'requests.view',
    'requests.assign',
    'deals.view',
    'documents.view',
    'documents.verify',
  ],
};
