export type AdminRole = 'broker' | 'agent';

export type AppPermission =
  | 'dashboard.view'
  | 'users.view'
  | 'users.create'
  | 'users.verify'
  | 'users.suspend'
  | 'categories.view'
  | 'forms.view'
  | 'posts.view'
  | 'offers.view'
  | 'buyers.view'
  | 'sellers.view'
  | 'marketplace.view'
  | 'marketplace.review'
  | 'requests.view'
  | 'requests.assign'
  | 'deals.view'
  | 'deals.manage'
  | 'payments.view'
  | 'mills.view'
  | 'disputes.view'
  | 'marketRates.view'
  | 'ratings.view'
  | 'alerts.view'
  | 'documents.view'
  | 'documents.verify'
  | 'analytics.view'
  | 'reports.view'
  | 'team.view'
  | 'account.view'
  | 'settings.view';
